### ISSUE TITLE
Cursor on the edit text box should be dark in color.

### ISSUE THREAD

**Issue by tusharmahawar** [WAHM-1521/PapaPoints#3]

**Comment by WAHM-1521** [comment]
in the layout file of main_activity,  Inside the TextField widget, add the cursorColor parameter and set the color to colorPrimaryDark.
android:textCursorDrawable = "@color/colorPrimaryDark"

**Comment by WAHM-1521** [comment]
Resolved

**Comment by WAHM-1521** [comment]
updated Main_activity layout to add textfield with 
android:textCursorDrawable = "@null"
